### ISSUE TITLE
Query nested tables from script

### ISSUE THREAD

**Issue by cgloeckner** [vinniefalco/LuaBridge#121] opened 2016-01-11 13:55 UTC
Hi, I'm trying to query nested tables from a script:

Minimal example:

``` c++
#include <cassert>
#include <iostream>
#include <lua5.2/lua.hpp>
#include <LuaBridge/LuaBridge.h>

int main() {
    lua_State* lua = luaL_newstate();
    luaL_openlibs(lua);
    assert(luaL_dofile(lua, "test.lua") == 0);
    auto first = luabridge::getGlobal(lua, "first");
    std::cout << first["second"]["actual"].cast<std::string>() << "\n";
}
```

Here's my script:

``` lua
first = {
    second = {
        actual = "data"
    }
}
```

The program crashs with 

```
PANIC: unprotected error in call to Lua API (attempt to index a nil value)
```

Further observation via

``` c++
assert(first.isTable());
assert(first["second"].isTable());
assert(first["second"].length() == 1); // fails
```

showed that the nested table "second" has no children at all.

What am I doing wrong? Or is it a bug in LuaBridge? I can still access nested tables via lua.

Thanks in advance

**Comment by Foaly** [comment] 2016-03-13 15:54
I am encountering the exact same problem. Did you find a solution for it?

**Comment by Foaly** [comment] 2016-03-14 18:26
I found a solution for the problem! I got a wonderful explanation from https://eliasdaler.wordpress.com/, who explained to me whats going on. I'll paraphrase:

The problem is this: 
```cpp 
auto first = luabridge::getGlobal(lua, "first");
```
You get luabridge::Proxy which is like a temporary reference which gets destroyed after this line. So, you need to convert it to luabridge::LuaRef like this:
```cpp 
luabridge::LuaRef first = luabridge::getGlobal(lua, "first");
// Or like this:
auto first = luabridge::LuaRef(luabridge::getGlobal(lua, "first"););
```
It is kind of annoying, but I guess this is the way LuaRef is working. Thanks again to elias daler and I hope this is useful to others as well!

**Comment by dmitry-t** [comment] 2018-09-06 21:36
Actually, there is no problem. Have you tried the following?
```
first = {
    second = {
        actual = "data"
    }
}
print (#first.second)
```
This prints `0`.
Moreover, `first.length()` is `0` too.

In the [Lua reference manual chapter 3.4.6 "The The Length Operator"](https://www.lua.org/manual/5.2/manual.html#3.4.6) it is stated:
> Unless a __len metamethod is given, the length of a table t is only defined if the table is a sequence, that is, the set of its positive numeric keys is equal to {1..n} for some non-negative integer n. In that case, n is its length.

Indeed, this code prints `1	1`:
```
first = { { "data " } }
print (#first, #first[1])
```

**Comment by dmitry-t** [comment] 2018-09-14 06:07
Expected behavior. Closing.

**Closed by dmitry-t** 2018-09-14 06:07 UTC
Labels: wait-for-response
